### PR TITLE
Add resource to creategenericevent(t)

### PR DESCRIPTION
**Pull request by MichaelYoung1981**

### CODE REVIEW

**Comment by scottcowan** [comment]
I'm not sure we need the Resource Type and can we add

```c#
    public interface IGenericEvent<T> : IEventView
    {
        DateTime CreatedOn { get; set; }
        T Payload { get; set; }
        string ResourceUri { get; set; }
        string ResourceId { get; set; }
    }
```

**Comment by MichaelYoung1981** [comment]
I've added the interface but I've left the ResourceType as I'm pretty sure we'll need it from MYA.

**Comment by scottcowan** [comment]
can you add a method to use the generic interface

```c#
        public async Task CreateGenericEvent(IGenericEvent<T> genericEvent)
```

and you can probably drop this method

```c#
        public async Task CreateGenericEvent<T>(T payLoad, string resourceUri = null, string resourceType = null, string resourceId = null)
```

**Comment by MichaelYoung1981** [comment]
Done.

**Comment by scottcowan** [comment]
I think this is ready to merge, I may come back with some changes after I've got the implementation done

**Pull request merged**
