### PR TITLE
ER-727 - Withdraw Application

### PR DESCRIPTION
**Pull request by chrisjensenuk**
Added `WithdrawApplication` method to client which adds a message to the new `application-withdrawn-queue` queue.

Note - v2 is not aware of FAA's application Id. So we target applications by CandidateId/VacancyReference combo.

### CODE REVIEW

**Comment by dev4valtech** [comment]
> Note - v2 is not aware of FAA's application Id. So we target applications by CandidateId/VacancyReference combo.

I think given that FAA clears applications and allows new ones . we should capture the Application Id so we do not take action on unrelated applications inadvertently.

**Comment by chrisjensenuk** [comment]
Cheers @dev4valtech one for @mgwilliam I think. I remember at the time we didn't want v2 to be exposed to FAA application Ids.

**Comment by chrisjensenuk** [comment]
@mgwilliam @dev4valtech I had a assumed the 'application id' that we require in v2 would be v2's applicationReviewId.  Do we really need to be aware of v1's applicaiton Id?

**Comment by dev4valtech** [comment]
@mgwilliam @chrisjensenuk As Mark stated we have business case for it now, however, in general terms when a system is not mastering the data it did better have exact identifier to reflect back with the data  source for any following incoming/outgoing messages/updates.

**Comment by chrisjensenuk** [comment]
I'm not sold but will change.

**Comment by dev4valtech** [comment]
Tough customer he!  One last try to convince you 🙂 
For example, we have case where applications messages are received by RAA and it fails to process due to Candidate-VacancyId constraint. The issue was the candidate was able to re-apply for the vacancy after the first one was deleted in FAA. We were able to come to this conclusion after finding that the application ids were different. Hence having a point of direct reference was useful.

**Comment by chrisjensenuk** [comment]
Couldn't you do the same with VacancyReference + CandidateId?

**Comment by dev4valtech** [comment]
Vacancy Ref and Candidate Ids were the same in the above case.

**Comment by chrisjensenuk** [comment]
I'd argue that it is because we have a leaky applicationId is the reason we had those issues with FAA/RAA. I can't get past "Has this candidate applied for this vacancy?". I don't need an application Id to answer this. CandidateId & VacancyReference is enough.  I'll catch up with you tomorrow :)

**Comment by chrisjensenuk** [comment]
Hi @dev4valtech I had a catch-up with @mgwilliam this morning.  We don't want to introduce v1's applicationId into v2 so identifying an application using the VacancyReference/CandidateId combo is OK. So I'm not going to change the functionality of this PR.

**Pull request merged**
