### PR TITLE
FC-472 Employer Menu

### PR DESCRIPTION
**Pull request by leewadhams**
The purpose of this package is to allow the sharing of the employer menu layout and functionality.
**Note:** Time spent on this has been minimal so expecting there to be improvement / tidy-up comments 😄 

The package is currently only consumed by Employer-Favourites (https://github.com/SkillsFundingAgency/das-employer-favourites/pull/19). I would expect there'll probably be some changes required to accommodate nuances of other apps.

Provides the following partial views (See readme in the package [folder](https://github.com/SkillsFundingAgency/das-shared-packages/tree/employer-menu/SFA.DAS.Employer.Shared.UI/SFA.DAS.Employer.Shared.UI) for more info):
- Menu 
- Header
- Footer

Configuration is shared between apps via table storage. (This is currently tied to the Employer-Favourites deployment). There's a meeting with DevOps to discuss the best option for this going forward.

### CODE REVIEW

**Comment by MichaelYoung1981** [comment]
Would it be helpful to add an example project?

**Comment by desderry** [comment]
instead of using viewbag properties to pass menu config, would this not make it a good candidate to be view components instead of partial views?

**Comment by leewadhams** [comment]
> Would it be helpful to add an example project?

Yep. Have added one in.

**Comment by leewadhams** [comment]
> Instead of using viewbag properties to pass menu config, would this not make it a good candidate to be view components instead of partial views? maybe one for the future :)

Yeah I'm not too happy with the ViewBag usage. The challenge is that the partials (or maybe components) sit on the _layout page but the settings, that the viewbag currently sets, can be different for some pages in a site. An example being some error pages don't show the menu but do show settings.

**Pull request merged**
